apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: demucs-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MINIO_HOST
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "rootuser"
            - name: MINIO_SECRET_KEY
              value: "rootpass123"
